package io.github.gyai.projects.devtools.skillvfx;

import io.github.gyai.projects.editor.core.*;
import java.util.*;

/** Mutable working draft separated from transport snapshots and widget state. */
public final class AbilityVisualEditorDocument implements EditorDocument {
    private SkillVfxModel.Snapshot baseline; private SkillVfxModel.Visual visual; private final EditorHistory<AbilityVisualEditorDocument> history=new EditorHistory<>(); private EditorSelection selection=EditorSelection.none();
    public AbilityVisualEditorDocument(SkillVfxModel.Snapshot snapshot){replaceBaseline(snapshot);}
    @Override public String id(){return baseline.abilityId();} public SkillVfxModel.Snapshot baseline(){return baseline;} public SkillVfxModel.Visual visual(){return visual;} public EditorHistory<AbilityVisualEditorDocument> history(){return history;} public EditorSelection selection(){return selection;} public void select(String kind,String id){selection=new EditorSelection(id==null?List.of():List.of(id),id);} void restoreSelection(EditorSelection value){selection=value==null?EditorSelection.none():value;}
    public boolean dirty(){return history.dirtyState()==DirtyState.DIRTY;} public void replaceBaseline(SkillVfxModel.Snapshot snapshot){baseline=Objects.requireNonNull(snapshot);visual=snapshot.visual();history.reset();history.markSaved();selection=EditorSelection.none();}
    /** Drops only local working-draft edits; it never sends server REVERT_VISUAL_SESSION. */
    public void discardDraft(){visual=baseline.visual();history.reset();history.markSaved();selection=EditorSelection.none();}
    public void acknowledge(SkillVfxModel.Snapshot snapshot){replaceBaseline(snapshot);} public void execute(EditorCommand<AbilityVisualEditorDocument> command){history.execute(this,command);} public void recordAlreadyApplied(EditorCommand<AbilityVisualEditorDocument> command){history.recordAlreadyApplied(this,command);} public boolean undo(){return history.undo(this);} public boolean redo(){return history.redo(this);}
    public Object selectedValue(String field){SkillVfxModel.Primitive p=selectedPrimitive();if(p==null)return null;return switch(field){case "delayTicks"->p.delayTicks();case "durationTicks"->p.durationTicks();case "argb"->p.argb();case "opacity"->(p.argb()>>>24)&255;case "width"->p.width();case "density"->p.density();case "seed"->p.seed();case "offsetX"->p.offset().x();case "offsetY"->p.offset().y();case "offsetZ"->p.offset().z();case "yaw"->p.yaw();case "controlPoints"->p.controls();default->p.value(field);};}
    /** Schema descriptor writer; accepted values are document commands, never widget-only state. */
    public void setSelectedValue(String field,Object value){SkillVfxModel.Primitive p=selectedPrimitive();if(p==null||field==null||value==null)return;if(field.equals("controlPoints")){if(value instanceof List<?> list&&list.stream().allMatch(SkillVfxModel.Vec.class::isInstance)&&withControls(p,list.stream().map(SkillVfxModel.Vec.class::cast).toList())!=null)execute(AbilityVisualCommands.setControlPoints(p.id(),list.stream().map(SkillVfxModel.Vec.class::cast).toList()));return;}SkillVfxModel.Primitive next=withSelectedValue(p,field,value);if(next!=null)execute(AbilityVisualCommands.replacePrimitive(p.id(),next));}
    public void setPrimitiveValue(String id,String field,SkillVfxModel.Scalar value){visual=mapPrimitive(visual,id,p->p.withValue(field,value));}
    public void setAppearance(String id,SkillVfxModel.Appearance appearance){visual=mapPrimitive(visual,id,p->p.withAppearance(appearance));}
    public void setControlPoints(String id,List<SkillVfxModel.Vec> controls){visual=mapPrimitive(visual,id,p->{SkillVfxModel.Primitive next=withControls(p,controls);return next==null?p:next;});}
    /** Replaces one primitive through a command.  Widgets never retain their own draft copy. */
    public void replacePrimitive(String id, SkillVfxModel.Primitive replacement){
        visual=mapPrimitive(visual,id,p->replacement);
    }
    public void addPrimitive(SkillVfxModel.Hook hook,String emissionId,SkillVfxModel.Primitive p){addPrimitive(hook,emissionId,p,Integer.MAX_VALUE);}
    public void addPrimitive(SkillVfxModel.Hook hook,String emissionId,SkillVfxModel.Primitive p,int index){visual=mapEmission(visual,hook,emissionId,e-> {ArrayList<SkillVfxModel.Primitive> x=new ArrayList<>(e.primitives());x.add(Math.clamp(index,0,x.size()),p);return new SkillVfxModel.Emission(e.id(),e.actionIndex(),x);});}
    /** Removing a final primitive removes its emission atomically; no invalid empty emission enters the draft. */
    public void removePrimitive(SkillVfxModel.Hook hook,String emissionId,String id){visual=mapEmission(visual,hook,emissionId,e->{ArrayList<SkillVfxModel.Primitive> x=new ArrayList<>(e.primitives());x.removeIf(p->p.id().equals(id));return x.isEmpty()?null:new SkillVfxModel.Emission(e.id(),e.actionIndex(),x);});}
    public void removePrimitive(String id){for(var h:visual.hooks())for(var e:h.emissions())if(e.primitives().stream().anyMatch(p->p.id().equals(id))){removePrimitive(h.hook(),e.id(),id);return;}} public void replaceVisual(SkillVfxModel.Visual next){visual=Objects.requireNonNull(next);}
    public void movePrimitive(SkillVfxModel.Hook hook,String emissionId,String id,int target){visual=mapEmission(visual,hook,emissionId,e->{ArrayList<SkillVfxModel.Primitive> x=new ArrayList<>(e.primitives());int at=-1;for(int n=0;n<x.size();n++)if(x.get(n).id().equals(id))at=n;if(at<0)return e;var p=x.remove(at);x.add(Math.clamp(target,0,x.size()),p);return new SkillVfxModel.Emission(e.id(),e.actionIndex(),x);});}
    public void addEmission(SkillVfxModel.Hook hook,SkillVfxModel.Emission emission){List<SkillVfxModel.HookBinding> hs=new ArrayList<>();boolean found=false;for(var h:visual.hooks()){if(h.hook()==hook){ArrayList<SkillVfxModel.Emission> es=new ArrayList<>(h.emissions());es.add(emission);hs.add(new SkillVfxModel.HookBinding(hook,es));found=true;}else hs.add(h);}if(!found)hs.add(new SkillVfxModel.HookBinding(hook,List.of(emission)));visual=visual.withHooks(hs);}
    public void removeEmission(SkillVfxModel.Hook hook,String id){visual=mapEmission(visual,hook,id,e->null);}
    public void moveEmission(SkillVfxModel.Hook hook,String id,int target){List<SkillVfxModel.HookBinding> hs=new ArrayList<>();for(var h:visual.hooks()){if(h.hook()!=hook){hs.add(h);continue;}ArrayList<SkillVfxModel.Emission> es=new ArrayList<>(h.emissions());int at=-1;for(int n=0;n<es.size();n++)if(es.get(n).id().equals(id))at=n;if(at>=0){var e=es.remove(at);es.add(Math.clamp(target,0,es.size()),e);}hs.add(new SkillVfxModel.HookBinding(hook,es));}visual=visual.withHooks(hs);}
    public void setEmissionActionIndex(SkillVfxModel.Hook hook,String id,int actionIndex){visual=mapEmission(visual,hook,id,e->new SkillVfxModel.Emission(e.id(),actionIndex,e.primitives()));}
    private SkillVfxModel.Primitive selectedPrimitive(){for(SkillVfxModel.HookBinding h:visual.hooks())for(SkillVfxModel.Emission e:h.emissions())for(SkillVfxModel.Primitive p:e.primitives())if(p.id().equals(selection.primaryId()))return p;return null;}
    private static SkillVfxModel.Primitive withSelectedValue(SkillVfxModel.Primitive p,String field,Object value){if(!Set.of("delayTicks","durationTicks","argb","opacity","width","density","seed","offsetX","offsetY","offsetZ","yaw","controlPoints").contains(field)){if(!(value instanceof SkillVfxModel.Scalar scalar))return null;if(field.equals("count")){if(!(scalar instanceof SkillVfxModel.Literal literal))return null;return p.withValue(field,new SkillVfxModel.Literal(Math.clamp(Math.rint(literal.value()),1,64)));}return p.withValue(field,scalar);}if(field.equals("controlPoints"))return value instanceof List<?> list&&list.stream().allMatch(SkillVfxModel.Vec.class::isInstance)?withControls(p,list.stream().map(SkillVfxModel.Vec.class::cast).toList()):null;if(!(value instanceof Number number)||!Double.isFinite(number.doubleValue()))return null;double raw=number.doubleValue();int delay=field.equals("delayTicks")?Math.max(0,(int)raw):p.delayTicks(),duration=field.equals("durationTicks")?Math.clamp((int)raw,1,1200):p.durationTicks(),density=field.equals("density")?Math.clamp((int)raw,1,256):p.density();int argb=field.equals("argb")?(int)raw:field.equals("opacity")?(Math.clamp((int)raw,0,255)<<24)|(p.argb()&0x00FFFFFF):p.argb();double width=field.equals("width")?Math.max(.001,raw):p.width();long seed=field.equals("seed")?(long)raw:p.seed();SkillVfxModel.Vec offset=new SkillVfxModel.Vec(field.equals("offsetX")?raw:p.offset().x(),field.equals("offsetY")?raw:p.offset().y(),field.equals("offsetZ")?raw:p.offset().z());return new SkillVfxModel.Primitive(p.id(),p.type(),delay,duration,argb,width,density,seed,offset,field.equals("yaw")?raw:p.yaw(),p.values(),p.controls(),p.appearance(),p.motion());}
    private static SkillVfxModel.Primitive withControls(SkillVfxModel.Primitive p,List<SkillVfxModel.Vec> controls){
        int size=controls.size();
        if((p.type()==SkillVfxModel.PrimitiveType.LINE&&size!=2)||(p.type()==SkillVfxModel.PrimitiveType.BEZIER&&(size<3||size>4))||(p.type()!=SkillVfxModel.PrimitiveType.LINE&&p.type()!=SkillVfxModel.PrimitiveType.BEZIER&&!controls.isEmpty())) return null;
        return new SkillVfxModel.Primitive(p.id(),p.type(),p.delayTicks(),p.durationTicks(),p.argb(),p.width(),p.density(),p.seed(),p.offset(),p.yaw(),p.values(),controls,p.appearance(),p.motion());
    }
    private static SkillVfxModel.Visual mapPrimitive(SkillVfxModel.Visual source,String id,java.util.function.Function<SkillVfxModel.Primitive,SkillVfxModel.Primitive> fn){List<SkillVfxModel.HookBinding> hs=new ArrayList<>();for(SkillVfxModel.HookBinding h:source.hooks()){List<SkillVfxModel.Emission> es=new ArrayList<>();for(SkillVfxModel.Emission e:h.emissions()){List<SkillVfxModel.Primitive> ps=new ArrayList<>();for(SkillVfxModel.Primitive p:e.primitives()){SkillVfxModel.Primitive n=p.id().equals(id)?fn.apply(p):p;if(n!=null)ps.add(n);}es.add(new SkillVfxModel.Emission(e.id(),e.actionIndex(),ps));}hs.add(new SkillVfxModel.HookBinding(h.hook(),es));}return source.withHooks(hs);}
    /** Structural deletion prunes the owning hook too, so drafts never carry empty bindings into Apply. */
    private static SkillVfxModel.Visual mapEmission(SkillVfxModel.Visual source,SkillVfxModel.Hook hook,String id,java.util.function.Function<SkillVfxModel.Emission,SkillVfxModel.Emission> fn){List<SkillVfxModel.HookBinding> hs=new ArrayList<>();for(SkillVfxModel.HookBinding h:source.hooks()){List<SkillVfxModel.Emission> es=new ArrayList<>();for(SkillVfxModel.Emission e:h.emissions()){SkillVfxModel.Emission next=h.hook()==hook&&e.id().equals(id)?fn.apply(e):e;if(next!=null)es.add(next);}if(!es.isEmpty())hs.add(new SkillVfxModel.HookBinding(h.hook(),es));}return source.withHooks(hs);}
}
