package io.github.gyai.projects.devtools.skillvfx;

import io.github.gyai.projects.client.vfx.AbilityVfx;import java.util.*;

/** Converts a selected draft hook to the same cue primitives consumed by the production renderer. */
public final class SkillVfxPreviewBuilder {
 private SkillVfxPreviewBuilder(){} public record Result(boolean valid,String message,AbilityVfx.Cue cue){}
 public static Result build(SkillVfxModel.Snapshot snapshot,SkillVfxModel.Visual visual,SkillVfxModel.Hook hook,AbilityVfx.Frame frame,UUID world,String dimension,long tick){try{if(snapshot==null||visual==null||hook==SkillVfxModel.Hook.TRAVEL||frame==null||world==null)return new Result(false,"Choose an editable hook and valid anchor",null);List<AbilityVfx.Primitive> primitives=new ArrayList<>();int duration=1;for(var e:visual.emissions(hook)){SkillVfxModel.GameplayAction action=e.actionIndex()>=0&&e.actionIndex()<snapshot.gameplay().size()?snapshot.gameplay().get(e.actionIndex()):null;for(var p:e.primitives()){primitives.add(convert(p,action));duration=Math.max(duration,p.delayTicks()+p.durationTicks());}}if(primitives.isEmpty())return new Result(false,"Selected hook has no primitives",null);var cue=new AbilityVfx.Cue(UUID.randomUUID(),1,UUID.randomUUID(),UUID.randomUUID(),visual.id(),AbilityVfx.Hook.valueOf(hook.name()),-1,0,world,dimension,frame,tick,tick,duration,List.copyOf(primitives));return new Result(true,"",cue);}catch(IllegalArgumentException e){return new Result(false,e.getMessage(),null);}}
 static AbilityVfx.Primitive convert(SkillVfxModel.Primitive p,SkillVfxModel.GameplayAction action){var appearance=p.appearance().kind()==AbilityVfx.AppearanceKind.DEBUG_QUAD?AbilityVfx.Appearance.DEBUG_QUAD:AbilityVfx.Appearance.particle(p.appearance().id());return new AbilityVfx.Primitive(AbilityVfx.Type.valueOf(p.type().name()),p.delayTicks(),p.durationTicks(),color(p.argb()),p.width(),p.density(),p.seed(),new AbilityVfx.Vec(p.offset().x(),p.offset().y(),p.offset().z()),p.yaw(),v(p,"size",action),v(p,"radius",action),v(p,"length",action),v(p,"height",action),v(p,"angle",action),v(p,"startAngle",action),v(p,"sweepAngle",action),v(p,"turns",action),(int)v(p,"count",action),p.controls().stream().map(x->new AbilityVfx.Vec(x.x(),x.y(),x.z())).toList(),appearance,p.motion());}
 private static double v(SkillVfxModel.Primitive p,String key,SkillVfxModel.GameplayAction action){var value=p.value(key);if(value==null)return 0;if(value instanceof SkillVfxModel.Literal l)return l.value();if(!(value instanceof SkillVfxModel.FromGameplay field)||action==null)throw new IllegalArgumentException("Invalid gameplay binding for "+key);String raw=switch(field.field()){case RADIUS->action.fields().get("radius");case INNER_RADIUS->action.fields().get("innerRadius");case WIDTH->action.fields().get("width");case LENGTH->action.fields().get("length");};if(raw==null)throw new IllegalArgumentException("Gameplay field unavailable: "+field.field());return Double.parseDouble(raw);}
 private static AbilityVfx.Color color(int argb){return new AbilityVfx.Color(argb>>>16&255,argb>>>8&255,argb&255,argb>>>24&255);}
}
