package io.github.gyai.projects.client.ui.icon;

/** Reusable pixel shapes. Multiple IDs may intentionally share one visual primitive. */
public enum ProjectSIconFallback {
    PLUS, MINUS, PENCIL, COPY, TRASH, FLOPPY, CHECK, RELOAD, UPLOAD, DOWNLOAD,
    UNDO, REDO, NODES, BARS, PALETTE, FLASK, SCRIPT, VARIABLE, CONDITION, EVENT,
    BEHAVIOR, GOAL, DROPS, SPAWN, EQUIPMENT, HEAD, SEARCH, FILTER, SORT, SETTINGS,
    CLOSE, BACK, NEXT, MENU, TAB, DROPDOWN, MORE, EXPAND, COLLAPSE, CHECKBOX_CHECKED,
    CHECKBOX_EMPTY, SUCCESS, WARNING, ERROR, INFO, LOCK, UNLOCK, EYE, EYE_HIDDEN,
    STAR, STAR_FILLED, PIN, DISABLED, SPINNER, MOB, ZOMBIE, SKELETON, CREEPER,
    SPIDER, ENDERMAN, VILLAGER, ANIMAL, BOSS, ELITE, HUMANOID, UNDEAD, SWORD,
    SHIELD, BOW, ARROW, MAGIC, HEAL, SPEED, ARMOR, CRITICAL, DAMAGE, PHYSICAL,
    MAGICAL, TRUE_DAMAGE, MELEE, RANGED, CAMERA, GRID, HITBOX, EYE_LINE, ROTATE,
    RESET, PLAY, PAUSE, STOP, FRONT_VIEW, BACK_VIEW, LEFT_VIEW, RIGHT_VIEW,
    HEAD_VIEW, LIGHT, BACKGROUND, CUBE, LAYERS, COLOR, TIME, BOOK, HELP, TAG,
    LINK, FOLDER, FILE,
    MISSING
}
