package io.github.gyai.projects.devtools;

import io.github.gyai.projects.devtools.skillvfx.*;import net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking;import net.minecraft.client.Minecraft;import net.minecraft.client.gui.screens.Screen;import java.util.*;

/** Session-aware client state; server snapshots remain the only authority and reconnect always starts clean. */
public final class SkillEditorClientState {
 private enum Wire { V1, V2 }
 private static UUID session;private static long nextCorrelation=1;private static long pendingCorrelation;private static UUID pendingRequestSession;private static SkillVfxEditorProtocol.Operation pendingOperation;private static SkillVfxEditorProtocol.State state;private static List<SkillVfxEditorProtocol.CatalogItem> catalog=List.of();private static Screen pendingParent;private static AbilityVisualEditorDocument document;private static boolean pending,refreshRequired,sessionApplyDenied;private static SkillEditorController.Feedback feedback=SkillEditorController.Feedback.NONE;private static String feedbackMessage="";private static long revision;private static Wire wire;
 private SkillEditorClientState(){}
 public static void receive(SkillVfxEditorProtocol.State value){receive(value,Wire.V1);}
 public static void receiveV2(SkillVfxEditorProtocol.State value){receive(value,Wire.V2);}
 private static void receive(SkillVfxEditorProtocol.State value,Wire inbound){
  if(value==null)return;
  if(wire!=null&&wire!=inbound)return;
  boolean malformedSentinel=pending&&value.status()==SkillVfxEditorProtocol.Status.MALFORMED&&value.correlation()==0;
  // Every ordinary envelope is a response to exactly one outstanding request.  Late,
  // unsolicited, and mismatched packets are intentionally inert.
  if(!pending||(!malformedSentinel&&value.correlation()!=pendingCorrelation))return;
  SkillVfxEditorProtocol.Operation operation=pendingOperation;
  if(value.status()==SkillVfxEditorProtocol.Status.PERMISSION_DENIED&&(operation==SkillVfxEditorProtocol.Operation.APPLY_VISUAL_SESSION||operation==SkillVfxEditorProtocol.Operation.REVERT_VISUAL_SESSION)&&!Objects.equals(value.session(),pendingRequestSession))return;
  boolean wasPending=true;pending=false;pendingOperation=null;pendingCorrelation=0;pendingRequestSession=null;revision++;
  if(malformedSentinel){feedback=SkillEditorController.Feedback.MALFORMED;feedbackMessage="Malformed server editor response; request cleared. Refresh to recover.";pendingParent=null;return;}
  // Apply/revert denial is operation-specific: the server sends an empty state envelope.
  // Keep the last authoritative snapshot and local dirty draft intact, but stop sending
  // session mutations for this connection.  Catalog, refresh, and preview remain usable.
  if(wasPending&&value.status()==SkillVfxEditorProtocol.Status.PERMISSION_DENIED&&(operation==SkillVfxEditorProtocol.Operation.APPLY_VISUAL_SESSION||operation==SkillVfxEditorProtocol.Operation.REVERT_VISUAL_SESSION)){
   sessionApplyDenied=true;feedback=SkillEditorController.Feedback.DENIED;feedbackMessage=value.message()==null?"Session visual changes are not permitted for this connection.":value.message();pendingParent=null;return;
  }
  feedback=wasPending?SkillEditorController.feedback(value.status(),operation==SkillVfxEditorProtocol.Operation.APPLY_VISUAL_SESSION):SkillEditorController.Feedback.NONE;feedbackMessage=value.message()==null?"":value.message();
  if(wasPending&&(value.status()==SkillVfxEditorProtocol.Status.STALE||value.status()==SkillVfxEditorProtocol.Status.CONFLICT)&&(operation==SkillVfxEditorProtocol.Operation.APPLY_VISUAL_SESSION||operation==SkillVfxEditorProtocol.Operation.REVERT_VISUAL_SESSION)){refreshRequired=true;pendingParent=null;return;}
  state=value;session=value.session();if(!value.catalog().isEmpty())catalog=List.copyOf(value.catalog());
  if(value.status()==SkillVfxEditorProtocol.Status.OK&&value.snapshot()!=null){var s=value.snapshot();var snapshot=new SkillVfxModel.Snapshot(value.session(),s.revision(),s.abilityId(),s.displayName(),s.visualId(),s.baseFingerprint(),s.effectiveFingerprint(),s.sessionOverride(),s.gameplay(),s.effective());
   if(operation==SkillVfxEditorProtocol.Operation.APPLY_VISUAL_SESSION||operation==SkillVfxEditorProtocol.Operation.REVERT_VISUAL_SESSION||document==null||!document.id().equals(snapshot.abilityId())) document=new AbilityVisualEditorDocument(snapshot);
   else document.replaceBaseline(snapshot);
   if(operation==SkillVfxEditorProtocol.Operation.FETCH)refreshRequired=false;
  }
  if(pendingParent!=null){if(value.status()==SkillVfxEditorProtocol.Status.OK){Minecraft.getInstance().setScreen(new SkillEditorScreen(pendingParent));}pendingParent=null;}
 }
 public static boolean open(Screen parent){pendingParent=parent;return send(SkillVfxEditorProtocol.Operation.CATALOG,"",0,"","",null);} public static boolean fetch(String ability){return send(SkillVfxEditorProtocol.Operation.FETCH,ability,0,"","",null);} public static boolean refresh(){return fetch(refreshAbility());} private static String refreshAbility(){return selectedAbility();} public static boolean revert(){if(sessionApplyDenied){feedback=SkillEditorController.Feedback.DENIED;feedbackMessage="Session visual changes are not permitted for this connection.";return false;}if(refreshRequired){feedback=SkillEditorController.Feedback.REFRESH_REQUIRED;feedbackMessage="Refresh server state before reverting this session.";return false;}return send(SkillVfxEditorProtocol.Operation.REVERT_VISUAL_SESSION,selectedAbility(),revision(),baseFingerprint(),effectiveFingerprint(),null);} public static boolean apply(){if(sessionApplyDenied){feedback=SkillEditorController.Feedback.DENIED;feedbackMessage="Session visual changes are not permitted for this connection.";return false;}if(refreshRequired||document==null||!document.dirty()||pending||session==null||session.equals(new UUID(0,0))){feedback=SkillEditorController.Feedback.REFRESH_REQUIRED;feedbackMessage=refreshRequired?"Refresh server state before applying this preserved draft.":"Apply is unavailable until a dirty server-backed visual is selected.";return false;}try{return send(SkillVfxEditorProtocol.Operation.APPLY_VISUAL_SESSION,selectedAbility(),revision(),baseFingerprint(),effectiveFingerprint(),SkillVfxEditorProtocol.encodeVisual(document.visual()),document.visual());}catch(RuntimeException error){feedback=SkillEditorController.Feedback.MALFORMED;feedbackMessage="Draft is locally invalid: "+(error.getMessage()==null?"repair the visual before applying.":error.getMessage());return false;}}
 public static boolean send(SkillVfxEditorProtocol.Operation operation,String ability,long requestRevision,String base,String effective,byte[] visual){return send(operation,ability,requestRevision,base,effective,visual,null);}
 private static boolean send(SkillVfxEditorProtocol.Operation operation,String ability,long requestRevision,String base,String effective,byte[] visual,SkillVfxModel.Visual appearanceVisual){if(pending)return false;Wire selected=wire;if(selected==null){if(operation!=SkillVfxEditorProtocol.Operation.CATALOG)return false;selected=ClientPlayNetworking.canSend(SkillEditorRequestPayloadV2.TYPE)?Wire.V2:ClientPlayNetworking.canSend(SkillEditorRequestPayload.TYPE)?Wire.V1:null;if(selected==null)return false;}if(selected==Wire.V2?!ClientPlayNetworking.canSend(SkillEditorRequestPayloadV2.TYPE):!ClientPlayNetworking.canSend(SkillEditorRequestPayload.TYPE))return false;try{long correlation=nextCorrelation++;UUID requestSession=session==null?new UUID(0,0):session;var request=new SkillVfxEditorProtocol.Request(operation,correlation,requestSession,ability==null?"":ability,requestRevision,base==null?"":base,effective==null?"":effective,visual);if(selected==Wire.V2)ClientPlayNetworking.send(new SkillEditorRequestPayloadV2(request,appearanceVisual));else ClientPlayNetworking.send(new SkillEditorRequestPayload(request));wire=selected;pending=true;pendingCorrelation=correlation;pendingRequestSession=requestSession;pendingOperation=operation;return true;}catch(RuntimeException e){feedback=SkillEditorController.Feedback.REFRESH_REQUIRED;feedbackMessage="Unable to send editor request";return false;}}
 public static SkillVfxEditorProtocol.State state(){return state;}public static List<SkillVfxEditorProtocol.CatalogItem> catalog(){return catalog;}public static AbilityVisualEditorDocument document(){return document;}public static boolean pending(){return pending;}public static boolean refreshRequired(){return refreshRequired;}public static boolean sessionApplyDenied(){return sessionApplyDenied;} public static long updateRevision(){return revision;}public static SkillEditorController.Feedback feedback(){return feedback;}public static String feedbackMessage(){return feedbackMessage;} public static boolean connected(){return wire==Wire.V2?ClientPlayNetworking.canSend(SkillEditorRequestPayloadV2.TYPE):wire==Wire.V1?ClientPlayNetworking.canSend(SkillEditorRequestPayload.TYPE):ClientPlayNetworking.canSend(SkillEditorRequestPayloadV2.TYPE)||ClientPlayNetworking.canSend(SkillEditorRequestPayload.TYPE);} public static boolean permitted(){return state!=null&&state.status()!=SkillVfxEditorProtocol.Status.PERMISSION_DENIED;} public static boolean previewAllowed(){return state!=null&&state.previewAllowed();} public static long revision(){return state!=null&&state.snapshot()!=null?state.snapshot().revision():0;}public static String selectedAbility(){return state!=null&&state.snapshot()!=null?state.snapshot().abilityId():!catalog.isEmpty()?catalog.getFirst().abilityId():"";}public static String baseFingerprint(){return state!=null&&state.snapshot()!=null?state.snapshot().baseFingerprint():"";}public static String effectiveFingerprint(){return state!=null&&state.snapshot()!=null?state.snapshot().effectiveFingerprint():"";} public static void reset(){io.github.gyai.projects.devtools.skillvfx.ui.SkillVfxWorldPreviewController.reset();session=null;state=null;catalog=List.of();document=null;pendingParent=null;pending=false;refreshRequired=false;sessionApplyDenied=false;pendingCorrelation=0;pendingRequestSession=null;pendingOperation=null;wire=null;feedback=SkillEditorController.Feedback.NONE;feedbackMessage="";nextCorrelation=1;revision++;}
}
