package io.github.gyai.projects.client.ui.theme;

public record ProjectSThemeTokens(
        int background,
        int backgroundAlt,
        int surface,
        int surfaceAlt,
        int surfaceRaised,
        int surfaceInput,
        int surfaceHover,
        int surfacePressed,
        int borderSubtle,
        int borderCard,
        int border,
        int borderStrong,
        int borderSelected,
        int textPrimary,
        int textSecondary,
        int textMuted,
        int textDisabled,
        int accentPrimary,
        int accentPrimaryHover,
        int accentPrimaryPressed,
        int accentCyan,
        int success,
        int warning,
        int danger,
        int info,
        int warningSurface,
        int dangerSurface,
        int overlay,
        int shadow,
        int focusGlow
) { }
