package io.github.gyai.projects.devtools.skillvfx.ui;

import io.github.gyai.projects.client.AbilityVfxLocalPreview;
import io.github.gyai.projects.client.ui.screen.ProjectSThemedScreen;
import io.github.gyai.projects.client.ui.theme.ProjectSThemeManager;
import io.github.gyai.projects.client.ui.widget.ProjectSButton;
import io.github.gyai.projects.devtools.SkillEditorScreen;
import io.github.gyai.projects.devtools.SkillEditorClientState;
import io.github.gyai.projects.devtools.skillvfx.*;
import io.github.gyai.projects.client.vfx.AbilityVfx;
import net.minecraft.client.input.KeyEvent;
import net.minecraft.client.input.MouseButtonEvent;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.client.renderer.state.level.CameraRenderState;
import net.minecraft.network.chat.Component;
import org.joml.Vector3f;
import org.lwjgl.glfw.GLFW;
import java.util.*;

/** Transparent, screen-owned authoring viewport. It never clears mc.screen or installs global input. */
public final class SkillVfx3dAuthoringScreen extends ProjectSThemedScreen {
    private final SkillEditorScreen owner; private final AbilityVfx.Frame frame; private final SkillVfx3dAuthoringLifecycle lifecycle=new SkillVfx3dAuthoringLifecycle(); private SkillVfxDirectAuthoring.DragTransaction drag; private SkillVfxDirectAuthoring.Handle dragHandle,hover; private SkillVfxDirectAuthoring.Projection cameraProjection; private SkillVfxDirectAuthoring.MotionHandleTarget motionHandleTarget=SkillVfxDirectAuthoring.MotionHandleTarget.PHASE; private String feedback=""; private boolean altHeld,cameraDragging,returning,editZ;
    private SkillVfx3dAuthoringScreen(SkillEditorScreen owner,AbilityVfx.Frame frame){super(Component.literal("VFX 3D編集"));this.owner=owner;this.frame=frame;}
    public static void open(SkillEditorScreen owner){if(owner==null)return;var frame=owner.begin3dAuthoring();var mc=net.minecraft.client.Minecraft.getInstance();if(frame==null||mc.getConnection()==null||mc.level==null||mc.player==null||owner.authoringPrimitive()==null)return;var screen=new SkillVfx3dAuthoringScreen(owner,frame);if(!screen.lifecycle.enter(screen,owner.worldPreviewDocument(),mc.getConnection(),mc.level,mc.level.dimension().identifier().toString(),owner.authoringPrimitive().id()))return;mc.setScreen(screen);}
    public SkillEditorScreen owner(){return owner;}
    public AbilityVfx.Frame frame(){return frame;}
    public void updateCamera(CameraRenderState cam){if(cam==null||cam.pos==null||cam.orientation==null||cam.projectionMatrix==null)return;Vector3f r=new Vector3f(1,0,0).rotate(cam.orientation),u=new Vector3f(0,1,0).rotate(cam.orientation),f=new Vector3f(0,0,-1).rotate(cam.orientation);double focal=Math.abs(cam.projectionMatrix.m11())*height/2d;try{cameraProjection=SkillVfxDirectAuthoring.fromBasis(new SkillVfxDirectAuthoring.Vec(r.x,r.y,r.z),new SkillVfxDirectAuthoring.Vec(u.x,u.y,u.z),new SkillVfxDirectAuthoring.Vec(f.x,f.y,f.z),new SkillVfxDirectAuthoring.Vec(cam.pos.x,cam.pos.y,cam.pos.z),focal);}catch(IllegalArgumentException ignored){cameraProjection=null;}}
    @Override protected void init(){int w=Math.min(262,Math.max(176,width-16)),x=8,y=8;addRenderableWidget(button(x,y,Math.min(98,w),owner.authoringPlaying()?"一時停止":"再生",()->runAndRefresh(()->owner.authoringToggle(frame))));addRenderableWidget(button(x+102,y,Math.min(62,w-102),"停止",()->runAndRefresh(()->owner.authoringStop(frame))));addRenderableWidget(button(x+168,y,Math.max(1,w-168),"最初から",()->runAndRefresh(()->owner.authoringRestart(frame))));addRenderableWidget(button(x,y+24,Math.min(96,w),owner.authoringLooping()?"ループ: オン":"ループ: オフ",()->runAndRefresh(owner::authoringLoop)));addRenderableWidget(button(x+100,y+24,Math.max(1,w-100),"Editorへ戻る",this::onClose));var p=owner.authoringPrimitive();boolean materialize=p!=null&&p.type()==SkillVfxModel.PrimitiveType.LINE&&p.controls().isEmpty();addRenderableWidget(button(x,y+48,Math.min(materialize?152:96,w),materialize?"始点・終点を設定":editZ?"点編集: Z":"点編集: XY",materialize?this::materializeLine:()->{editZ=!editZ;clearWidgets();init();}));var direction=button(x,y+72,Math.min(152,w),p==null?"方向":"方向: "+MotionAuthoringPresentation.label(p.motion().direction()),()->runAndRefresh(owner::toggleMotionDirection));direction.active=p!=null&&SkillEditorClientState.supportsEditorV3()&&MotionAuthoringPresentation.canToggleDirection(p.type(),p.motion());addRenderableWidget(direction);var motionControl=MotionAuthoringPresentation.motionHandleControl(width,p,motionHandleTarget);if(motionControl.visible()){var target=button(motionControl.x(),motionControl.y(),motionControl.width(),motionControl.label(),()->{motionHandleTarget=motionHandleTarget==SkillVfxDirectAuthoring.MotionHandleTarget.PHASE?SkillVfxDirectAuthoring.MotionHandleTarget.TRAIL:SkillVfxDirectAuthoring.MotionHandleTarget.PHASE;clearWidgets();init();});target.active=motionControl.enabled();addRenderableWidget(target);}}
    private void runAndRefresh(Runnable action){action.run();clearWidgets();init();}
    private ProjectSButton button(int x,int y,int w,String label,Runnable action){return new ProjectSButton(x,y,Math.max(1,w),20,Component.literal(label),ProjectSButton.Kind.SECONDARY,action);}
    @Override public void tick(){super.tick();var mc=net.minecraft.client.Minecraft.getInstance();if(!lifecycle.valid(this,owner.worldPreviewDocument(),mc.getConnection(),mc.level,mc.level==null?"":mc.level.dimension().identifier().toString(),mc.player!=null&&mc.player.isAlive())){invalidate();return;}owner.advanceDetachedWorldPreview();}
    @Override public void mouseMoved(double x,double y){var p=owner.authoringPrimitive();hover=p==null?null:hit(p,x,y).map(SkillVfxDirectAuthoring.Pick::handle).orElse(null);super.mouseMoved(x,y);}
    @Override public void extractRenderState(net.minecraft.client.gui.GuiGraphicsExtractor graphics,int mouseX,int mouseY,float tickProgress){var t=ProjectSThemeManager.get().activeTheme().tokens();int w=Math.min(262,Math.max(176,width-16));graphics.fill(5,5,8+w,122,0xB4000000);graphics.text(font,"VFX 3D編集",8,10,t.accentPrimary(),false);var p=owner.authoringPrimitive();graphics.text(font,(p==null?"":SkillVfxDisplay.hook(owner.authoringHook())+" > "+SkillVfxDisplay.primitive(p.type()))+" / " +(p==null?"":p.appearance().id()),8,46,t.textPrimary(),false);graphics.text(font,"移動・形  •  点: "+(editZ?"Z":"XY")+"  •  Alt+ドラッグ: 視点",8,58,t.textMuted(),false);if(hover!=null)graphics.text(font,hover.label()+" をドラッグして編集",8,70,t.accentPrimary(),false);if(p!=null&&p.type()==SkillVfxModel.PrimitiveType.LINE&&p.controls().isEmpty())graphics.text(font,"始点・終点を設定して直接編集",8,82,t.accentPrimary(),false);else if(!feedback.isBlank())graphics.text(font,feedback,8,82,t.accentPrimary(),false);super.extractRenderState(graphics,mouseX,mouseY,tickProgress);}
    @Override public boolean mouseClicked(MouseButtonEvent event,boolean doubleClick){if(super.mouseClicked(event,doubleClick))return true;if(event.button()!=0)return true;if(altHeld){cameraDragging=true;return true;}var p=owner.authoringPrimitive();var d=owner.worldPreviewDocument();if(p==null||d==null)return true;var hit=hit(p,event.x(),event.y());if(hit.isEmpty())return true;dragHandle=hit.get().handle();drag=SkillVfxDirectAuthoring.DragTransaction.begin(d,p.id()).orElse(null);feedback=dragHandle.label();return true;}
    @Override public boolean mouseDragged(MouseButtonEvent event,double dx,double dy){if(cameraDragging){if(minecraft.player!=null)minecraft.player.turn((float)dx,(float)dy);return true;}if(drag==null||dragHandle==null||cameraProjection==null)return true;if(dragHandle.kind()==SkillVfxDirectAuthoring.Handle.Kind.PHASE||dragHandle.kind()==SkillVfxDirectAuthoring.Handle.Kind.TRAIL){drag.update(p->SkillVfxDirectAuthoring.editAtMouse(p,dragHandle,frame,owner.authoringAction(),owner.authoringProgress(),cameraProjection,event.x()-width/2.0,height/2.0-event.y()));}else{var delta=SkillVfxDirectAuthoring.dragDelta(drag.current(),dragHandle,frame,cameraProjection,dx,-dy,editZ);drag.update(p->SkillVfxDirectAuthoring.edit(p,dragHandle,delta.x(),delta.y(),editZ));}owner.authoringPreviewChanged(frame);feedback=dragHandle.label()+" "+SkillVfxDirectAuthoring.value(drag.current(),dragHandle);return true;}
    @Override public boolean mouseReleased(MouseButtonEvent event){if(event.button()==0)cameraDragging=false;if(drag!=null&&event.button()==0){drag.release();drag=null;dragHandle=null;return true;}return true;}
    @Override public boolean keyPressed(KeyEvent event){if(event.key()==GLFW.GLFW_KEY_LEFT_ALT||event.key()==GLFW.GLFW_KEY_RIGHT_ALT){altHeld=true;return true;}if(event.key()==GLFW.GLFW_KEY_ESCAPE&&drag!=null){drag.cancel();drag=null;dragHandle=null;owner.authoringPreviewChanged(frame);feedback="キャンセル";return true;}if(super.keyPressed(event))return true;return true;}
    @Override public boolean keyReleased(KeyEvent event){if(event.key()==GLFW.GLFW_KEY_LEFT_ALT||event.key()==GLFW.GLFW_KEY_RIGHT_ALT){altHeld=false;return true;}return true;}
    @Override public void onClose(){var mc=net.minecraft.client.Minecraft.getInstance();if(!lifecycle.returning(this,owner.worldPreviewDocument(),mc.getConnection(),mc.level,mc.level==null?"":mc.level.dimension().identifier().toString(),mc.player!=null&&mc.player.isAlive())){invalidate();return;}if(drag!=null){drag.cancel();drag=null;owner.authoringPreviewChanged(frame);}returning=true;lifecycle.clear();owner.authoringReturned();minecraft.setScreen(owner);}
    @Override public void removed(){if(!returning&&lifecycle.active())invalidate();super.removed();}
    private void invalidate(){if(drag!=null){drag.cancel();drag=null;dragHandle=null;}AbilityVfxLocalPreview.stop();lifecycle.clear();returning=true;if(minecraft.screen==this)minecraft.setScreen(null);}
    private void materializeLine(){var p=owner.authoringPrimitive();if(p!=null&&SkillVfxDirectAuthoring.materializeLine(owner.worldPreviewDocument(),p.id())){owner.authoringPreviewChanged(frame);feedback="始点・終点を設定しました";clearWidgets();init();}}
    public SkillVfxDirectAuthoring.MotionHandleTarget motionHandleTarget(){var p=owner.authoringPrimitive();var control=MotionAuthoringPresentation.motionHandleControl(width,p,motionHandleTarget);return control.visible()?motionHandleTarget==SkillVfxDirectAuthoring.MotionHandleTarget.TRAIL&&control.enabled()?SkillVfxDirectAuthoring.MotionHandleTarget.TRAIL:SkillVfxDirectAuthoring.MotionHandleTarget.PHASE:SkillVfxDirectAuthoring.MotionHandleTarget.NONE;}
    private Optional<SkillVfxDirectAuthoring.Pick> hit(SkillVfxModel.Primitive p,double x,double y){if(cameraProjection==null)return Optional.empty();return SkillVfxDirectAuthoring.pick(SkillVfxDirectAuthoring.selectableMotionHandles(p,frame,owner.authoringAction(),owner.authoringProgress(),motionHandleTarget()),cameraProjection,x-width/2.0,height/2.0-y,12);}
}
