package io.github.gyai.projects.client.vfx;

import java.io.*;
import java.nio.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.*;
import java.util.*;

/** Contract regression suite intentionally runnable without Fabric/Minecraft. */
public final class AbilityVfxClientTest {
  static final UUID S=UUID.fromString("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"), C=UUID.fromString("01234567-89ab-cdef-0123-456789abcdef"), CAST=UUID.fromString("fedcba98-7654-3210-fedc-ba9876543210"), W=UUID.fromString("11111111-2222-3333-4444-555555555555");
  public static void main(String[] args) throws Exception { geometry(); lifecycle(); policy(); decoder(); validationVectors(); golden(); }
  static void geometry(){
    AbilityVfx.Frame identity=new AbilityVfx.Frame(new AbilityVfx.Vec(10,20,30),new AbilityVfx.Vec(0,0,1),new AbilityVfx.Vec(0,1,0));
    AbilityVfx.Frame rotated=new AbilityVfx.Frame(new AbilityVfx.Vec(10,20,30),new AbilityVfx.Vec(1,0,0),new AbilityVfx.Vec(0,1,0));
    for(AbilityVfx.Type t:AbilityVfx.Type.values()) { AbilityVfx.Primitive p=p(t); var z=AbilityVfx.sample(p,identity,0,AbilityVfx.Quality.HIGH);var h=AbilityVfx.sample(p,identity,.5,AbilityVfx.Quality.HIGH);var o=AbilityVfx.sample(p,identity,1,AbilityVfx.Quality.HIGH);assert !z.isEmpty()&&!h.isEmpty()&&!o.isEmpty()&&o.size()<=512;assert o.equals(AbilityVfx.sample(p,identity,1,AbilityVfx.Quality.HIGH));for(var c:o)assert c.a().finite()&&(c.b()==null||c.b().finite()); }
    var line=AbilityVfx.sample(p(AbilityVfx.Type.LINE),identity,1,AbilityVfx.Quality.HIGH);assert near(line.getFirst().a().x(),10)&&near(line.getLast().b().z(),34);
    var rotatedLine=AbilityVfx.sample(p(AbilityVfx.Type.LINE),rotated,1,AbilityVfx.Quality.HIGH);assert near(rotatedLine.getLast().b().x(),14)&&near(rotatedLine.getLast().b().z(),30);
    var arc=AbilityVfx.sample(p(AbilityVfx.Type.ARC),identity,1,AbilityVfx.Quality.HIGH);assert !arc.getFirst().a().equals(arc.getLast().b());
    var circle=AbilityVfx.sample(p(AbilityVfx.Type.CIRCLE),identity,1,AbilityVfx.Quality.HIGH);assert near(circle.getFirst().a().x(),circle.getLast().b().x())&&near(circle.getFirst().a().z(),circle.getLast().b().z());
    var burst=AbilityVfx.sample(p(AbilityVfx.Type.BURST),identity,1,AbilityVfx.Quality.HIGH);assert burst.size()==8&&!burst.getFirst().equals(burst.get(1));
    var point=AbilityVfx.sample(p(AbilityVfx.Type.POINT),identity,1,AbilityVfx.Quality.HIGH).getFirst();assert point.b()==null&&near(point.width(),1);
    assert AbilityVfx.sample(p(AbilityVfx.Type.CONE),identity,1,AbilityVfx.Quality.HIGH).getLast().b().z()>33;
    for(var ray:AbilityVfx.sample(p(AbilityVfx.Type.CONE),identity,1,AbilityVfx.Quality.HIGH))assert near(ray.a().x(),10)&&near(ray.a().y(),20)&&near(ray.a().z(),30);
    for(var ray:burst)assert near(ray.a().x(),10)&&near(ray.a().y(),20)&&near(ray.a().z(),30)&&Math.hypot(ray.b().x()-10,ray.b().z()-30)<=4.00001;
    assert near(AbilityVfx.sample(p(AbilityVfx.Type.SPIRAL),identity,1,AbilityVfx.Quality.HIGH).getLast().b().y(),22);
    assert near(AbilityVfx.sample(p(AbilityVfx.Type.SPHERE),identity,1,AbilityVfx.Quality.HIGH).getLast().b().y(),16);
    assert near(AbilityVfx.sample(p(AbilityVfx.Type.WAVE),identity,1,AbilityVfx.Quality.HIGH).getLast().b().z(),34);
    assert near(AbilityVfx.sample(p(AbilityVfx.Type.BEZIER),identity,1,AbilityVfx.Quality.HIGH).getLast().b().x(),14);
    assert AbilityVfx.sample(p(AbilityVfx.Type.CIRCLE),identity,1,AbilityVfx.Quality.LOW).size()<AbilityVfx.sample(p(AbilityVfx.Type.CIRCLE),identity,1,AbilityVfx.Quality.HIGH).size();
  }
  static void lifecycle(){
    AbilityVfxStore s=new AbilityVfxStore(); AbilityVfx.Cue one=cue(S,1,C,CAST,AbilityVfx.Hook.CAST);assert s.receive(new AbilityVfx.Decoded(true,one),W.toString(),"minecraft:overworld",0);assert !s.receive(new AbilityVfx.Decoded(true,one),W.toString(),"minecraft:overworld",0);assert !s.receive(new AbilityVfx.Decoded(true,cue(S,1,UUID.randomUUID(),CAST,AbilityVfx.Hook.CAST)),W.toString(),"minecraft:overworld",0);s.tick(1200,W.toString(),"minecraft:overworld");assert s.size()==0;
    UUID newer=UUID.randomUUID();AbilityVfx.Cue n=cue(newer,1,UUID.randomUUID(),CAST,AbilityVfx.Hook.CAST);assert s.receive(new AbilityVfx.Decoded(true,n),W.toString(),"minecraft:overworld",0);assert !s.receive(new AbilityVfx.Decoded(true,cue(S,99,UUID.randomUUID(),CAST,AbilityVfx.Hook.CAST)),W.toString(),"minecraft:overworld",0);s.tick(1,null,null);assert !s.receive(new AbilityVfx.Decoded(true,cue(S,100,UUID.randomUUID(),CAST,AbilityVfx.Hook.CAST)),W.toString(),"minecraft:overworld",0);s.resetConnection();assert s.receive(new AbilityVfx.Decoded(true,cue(S,1,UUID.randomUUID(),CAST,AbilityVfx.Hook.CAST)),W.toString(),"minecraft:overworld",0);
    AbilityVfx.Cue terminal=cue(S,2,UUID.randomUUID(),CAST,AbilityVfx.Hook.CANCEL);assert s.receive(new AbilityVfx.Decoded(true,terminal),W.toString(),"minecraft:overworld",1)&&s.size()==1;s.tick(2,W.toString(),"minecraft:the_nether");assert s.size()==0;
    AbilityVfx.Primitive delayed=new AbilityVfx.Primitive(AbilityVfx.Type.POINT,5,3,new AbilityVfx.Color(1,2,3,4),.5,1,0,new AbilityVfx.Vec(0,0,0),0,1,0,0,0,0,0,0,0,0,List.of());AbilityVfx.Cue delayedCue=new AbilityVfx.Cue(S,3,UUID.randomUUID(),UUID.randomUUID(),"projects:vfx/test",AbilityVfx.Hook.CAST,-1,0,W,"minecraft:overworld",new AbilityVfx.Frame(new AbilityVfx.Vec(0,0,0),new AbilityVfx.Vec(0,0,1),new AbilityVfx.Vec(0,1,0)),0,0,20,List.of(delayed));AbilityVfxStore.Active active=new AbilityVfxStore.Active(delayedCue,10);assert !active.isPrimitiveActive(14,delayed)&&active.isPrimitiveActive(15,delayed)&&active.isPrimitiveActive(17,delayed)&&!active.isPrimitiveActive(18,delayed)&&near(active.progress(15,delayed),0);
    s.resetConnection();UUID castA=UUID.randomUUID(),castB=UUID.randomUUID();assert s.receive(new AbilityVfx.Decoded(true,cue(S,1,UUID.randomUUID(),castA,AbilityVfx.Hook.CAST)),W.toString(),"minecraft:overworld",0);assert s.receive(new AbilityVfx.Decoded(true,cue(S,2,UUID.randomUUID(),castB,AbilityVfx.Hook.CAST)),W.toString(),"minecraft:overworld",0);assert s.receive(new AbilityVfx.Decoded(true,cue(S,3,UUID.randomUUID(),castA,AbilityVfx.Hook.CANCEL)),W.toString(),"minecraft:overworld",0)&&s.size()==2;assert s.receive(new AbilityVfx.Decoded(true,cue(S,4,UUID.randomUUID(),castA,AbilityVfx.Hook.EXPIRE)),W.toString(),"minecraft:overworld",0)&&s.size()==3;
    s.resetConnection();for(int i=1;i<=64;i++)assert s.receive(new AbilityVfx.Decoded(true,cue(S,i,UUID.randomUUID(),UUID.randomUUID(),AbilityVfx.Hook.CAST)),W.toString(),"minecraft:overworld",0);assert s.size()==64;assert !s.receive(new AbilityVfx.Decoded(true,cue(S,65,UUID.randomUUID(),UUID.randomUUID(),AbilityVfx.Hook.CAST)),W.toString(),"minecraft:overworld",0);
  }
  static void policy(){assert AbilityVfxRenderPolicy.withinDistance(96,0,0)&&!AbilityVfxRenderPolicy.withinDistance(96.01,0,0);assert AbilityVfxRenderPolicy.allow(900,0,0)==512;assert AbilityVfxRenderPolicy.allow(512,2000,8000)==48;assert AbilityVfxRenderPolicy.allow(512,0,7680)==512;assert AbilityVfxRenderPolicy.allow(512,0,7681)==511;assert AbilityVfxRenderPolicy.allow(512,0,8192)==0;int frame=0;for(int cue=0;cue<32;cue++){int cueUsed=0;for(int primitive=0;primitive<16;primitive++){int allowed=AbilityVfxRenderPolicy.allow(512,cueUsed,frame+cueUsed);cueUsed+=allowed;}assert cueUsed<=2048;frame+=cueUsed;}assert frame==AbilityVfxRenderPolicy.FRAME_BUDGET;}
  static void decoder() throws Exception {
    byte[] b=wire();assert AbilityVfx.decode(b).valid();int h=header();int primitive=h+93;
    byte[] x=b.clone();x[0]=2;bad(x);x=b.clone();x[1+16+8+16+16+2+"projects:vfx/test".length()]=99;bad(x);x=b.clone();ByteBuffer.wrap(x).order(ByteOrder.BIG_ENDIAN).putDouble(h,Double.NaN);bad(x);x=b.clone();ByteBuffer.wrap(x).order(ByteOrder.BIG_ENDIAN).putDouble(h+8,Double.POSITIVE_INFINITY);bad(x);
    for(int cut:new int[]{0,1,20,b.length-1})bad(Arrays.copyOf(b,cut));bad(Arrays.copyOf(b,b.length+1));bad(new byte[16385]);
    x=b.clone();x[h+88]=99;bad(x);x=b.clone();ByteBuffer.wrap(x).order(ByteOrder.BIG_ENDIAN).putInt(h+88,400).putShort(primitive+4,(short)200);assert AbilityVfx.decode(x).valid();x=b.clone();ByteBuffer.wrap(x).order(ByteOrder.BIG_ENDIAN).putInt(h+88,400).putShort(primitive+4,(short)201);bad(x);x=b.clone();x[h+92]=17;bad(x);x=b.clone();x[primitive+1]=2; // unknown version is skipped -> all unknown
    bad(x);x=b.clone();x[primitive]=(byte)250;bad(x);x=b.clone();x[primitive+4+124]=9;bad(x);x=b.clone();ByteBuffer.wrap(x).order(ByteOrder.BIG_ENDIAN).putInt(1+16+8+16+16+2+"projects:vfx/test".length()+1,-2);bad(x);
    x=Arrays.copyOf(b,b.length+5);x[x.length-5]=(byte)250;x[x.length-4]=1;x[x.length-3]=0;x[x.length-2]=1;x[x.length-1]=7;x[h+92]=2;assert AbilityVfx.decode(x).valid();
  }
  static void validationVectors() throws Exception {
    Set<String> expected=Set.of("CONE_ANGLE_NEXT_DOWN_PI","CONE_ANGLE_PI","CONE_ANGLE_NEXT_UP_PI","CONE_ANGLE_POSITIVE_ZERO","CONE_ANGLE_NEGATIVE_ZERO","CONE_ANGLE_NEGATIVE","CIRCLE_SIZE_POSITIVE_ZERO","CIRCLE_SIZE_NEGATIVE_ZERO","CIRCLE_RADIUS_POSITIVE_ZERO","CIRCLE_RADIUS_NEGATIVE_ZERO","CIRCLE_RADIUS_ORDINARY");
    Set<String> actual=new HashSet<>(); for(String line:Files.readAllLines(Path.of("src/test/resources/protocol/ability-vfx-validation-v1.txt"))){if(!line.isBlank()&&!line.startsWith("#")){String[] columns=line.split("\\|",-1);assert columns.length==5&&(columns[4].equals("ACCEPT")||columns[4].equals("REJECT"));actual.add(columns[0]);}} assert actual.equals(expected);
    assert AbilityVfx.decode(coneWire(Math.nextDown(Math.PI))).valid(); for(double angle:new double[]{Math.PI,Math.nextUp(Math.PI),0.0,-0.0,-1.0})bad(coneWire(angle));
    for(double size:new double[]{0.0,-0.0}){byte[] x=wire();putPrimitiveDouble(x,58,size);assert AbilityVfx.decode(x).valid();} for(double radius:new double[]{0.0,-0.0}){byte[] x=wire();putPrimitiveDouble(x,66,radius);bad(x);} assert AbilityVfx.decode(wire()).valid();
  }
  static void golden() throws Exception {String text=Files.readString(Path.of("src/test/resources/protocol/ability-vfx-v1-golden.hex"));assert sha(text.getBytes(StandardCharsets.UTF_8)).equals("20144ABB25012915AD872DBFDAF599AD28EE1698ADF993145C1E71E225257091");byte[] raw=hex(text.trim());assert sha(raw).equals("C1E1C796505487AC5BB52D12F982C3EF77C645220D412C743AFCEFC85C4B1BB3");AbilityVfx.Decoded d=AbilityVfx.decode(raw);assert d.valid();var c=d.cue();assert c.session().equals(S)&&c.sequence()==7&&c.cueId().equals(C)&&c.castId().equals(CAST)&&c.visualId().equals("projects:vfx/golden")&&c.hook()==AbilityVfx.Hook.TELEGRAPH&&c.actionIndex()==0&&c.emissionIndex()==0&&c.worldId().equals(W)&&c.dimension().equals("minecraft:overworld")&&near(c.frame().origin().x(),1.25)&&near(c.frame().origin().y(),64)&&near(c.frame().origin().z(),-2.5)&&c.serverTick()==100&&c.startTick()==100&&c.duration()==22&&c.primitives().size()==1&&c.primitives().getFirst().type()==AbilityVfx.Type.CIRCLE;}
  static AbilityVfx.Primitive p(AbilityVfx.Type t){return new AbilityVfx.Primitive(t,0,100,new AbilityVfx.Color(1,2,3,4),.5,32,7,new AbilityVfx.Vec(0,0,0),0,1,4,4,2,1,0,Math.PI,2,8,List.of(new AbilityVfx.Vec(0,0,0),new AbilityVfx.Vec(0,0,4),new AbilityVfx.Vec(2,1,6),new AbilityVfx.Vec(4,0,8)));}
  static AbilityVfx.Cue cue(UUID s,long q,UUID id,UUID cast,AbilityVfx.Hook h){return new AbilityVfx.Cue(s,q,id,cast,"projects:vfx/test",h,-1,0,W,"minecraft:overworld",new AbilityVfx.Frame(new AbilityVfx.Vec(0,0,0),new AbilityVfx.Vec(0,0,1),new AbilityVfx.Vec(0,1,0)),0,0,1200,List.of(p(AbilityVfx.Type.POINT)));}
  static boolean near(double a,double b){return Math.abs(a-b)<.0001;}static void bad(byte[] x){assert !AbilityVfx.decode(x).valid();}static String sha(byte[] x)throws Exception{byte[] h=MessageDigest.getInstance("SHA-256").digest(x);StringBuilder b=new StringBuilder();for(byte q:h)b.append(String.format("%02X",q));return b.toString();}static byte[] hex(String x){byte[] b=new byte[x.length()/2];for(int i=0;i<b.length;i++)b[i]=(byte)Integer.parseInt(x.substring(i*2,i*2+2),16);return b;}
  static int header(){return 1+16+8+16+16+2+"projects:vfx/test".length()+1+4+4+16+2+"minecraft:overworld".length();}
  static byte[] coneWire(double angle) throws Exception {byte[] x=wire();int primitive=header()+93;x[primitive]=(byte)AbilityVfx.Type.CONE.ordinal();putPrimitiveDouble(x,66,0);putPrimitiveDouble(x,74,4);putPrimitiveDouble(x,90,angle);return x;} static void putPrimitiveDouble(byte[] x,int field,double value){ByteBuffer.wrap(x).order(ByteOrder.BIG_ENDIAN).putDouble(header()+93+4+field,value);}
  static byte[] wire() throws Exception {ByteArrayOutputStream os=new ByteArrayOutputStream();DataOutputStream d=new DataOutputStream(os);d.writeByte(1);uuid(d,S);d.writeLong(1);uuid(d,C);uuid(d,CAST);str(d,"projects:vfx/test");d.writeByte(0);d.writeInt(-1);d.writeInt(0);uuid(d,W);str(d,"minecraft:overworld");for(double q:new double[]{0,0,0,0,0,1,0,1,0})d.writeDouble(q);d.writeLong(0);d.writeLong(0);d.writeInt(100);d.writeByte(1);d.writeByte(AbilityVfx.Type.CIRCLE.ordinal());d.writeByte(1);d.writeShort(125);d.writeShort(0);d.writeShort(100);d.write(new byte[]{1,2,3,4});d.writeDouble(1);d.writeShort(32);d.writeLong(7);for(int i=0;i<3;i++)d.writeDouble(0);d.writeDouble(0);for(double q:new double[]{0,4,0,0,0,0,0,0})d.writeDouble(q);d.writeShort(0);d.writeByte(0);return os.toByteArray();}static void uuid(DataOutputStream d,UUID u)throws Exception{d.writeLong(u.getMostSignificantBits());d.writeLong(u.getLeastSignificantBits());}static void str(DataOutputStream d,String s)throws Exception{byte[] b=s.getBytes(StandardCharsets.UTF_8);d.writeShort(b.length);d.write(b);}
}
