package io.github.gyai.projects.devtools.skillvfx;

import java.util.*;

public final class SkillVfxEditorModelTest {
 public static void main(String[] args)throws Exception{
  String hex=java.nio.file.Files.readString(java.nio.file.Path.of("devtools/src/test/resources/protocol/skill-vfx-editor-v1-golden.hex")).replaceAll("\\s","");
  byte[] wire=java.util.HexFormat.of().parseHex(hex);
  assert java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(wire)).equals("7178538049f2a7ac6807f1a3190e6840ebb0c8b6690c42a56090612383a4fdd4");
  var state=SkillVfxEditorProtocol.decodeState(wire);
  assert state.status()==SkillVfxEditorProtocol.Status.OK&&state.correlation()==7&&state.catalog().size()==2&&state.catalog().get(0).hasVisual()&&!state.catalog().get(1).hasVisual()&&state.catalog().get(1).visualId().isEmpty();
  assert state.snapshot()!=null&&state.snapshot().abilityId().equals("projects:dev-shared-arcane-burst");
  assert state.snapshot().gameplay().getFirst().type().equals("CircleTelegraph");
  var telegraph=state.snapshot().effective().emissions(SkillVfxModel.Hook.TELEGRAPH).getFirst().primitives().getFirst();
  assert telegraph.value("radius") instanceof SkillVfxModel.FromGameplay&&((SkillVfxModel.FromGameplay)telegraph.value("radius")).field()==SkillVfxModel.ActionField.RADIUS;
  assert java.util.Arrays.equals(wire,SkillVfxEditorProtocol.encodeState(state));
  for(var type:SkillVfxModel.PrimitiveType.values()){var p=SkillVfxModel.defaults("p-"+type,type);assert AbilityVisualPropertySchemas.fields(type).size()>=12;assert p.type()==type;}
  var circle=SkillVfxModel.defaults("telegraph-circle",SkillVfxModel.PrimitiveType.CIRCLE).withValue("radius",new SkillVfxModel.FromGameplay(SkillVfxModel.ActionField.RADIUS));
  var emission=new SkillVfxModel.Emission("telegraph",0,List.of(circle));var visual=new SkillVfxModel.Visual("projects:vfx/arcane",List.of(new SkillVfxModel.HookBinding(SkillVfxModel.Hook.TELEGRAPH,List.of(emission))));
  var snapshot=new SkillVfxModel.Snapshot(UUID.randomUUID(),1,"projects:arcane-burst","Arcane Burst",visual.id(),"base","effective",false,List.of(new SkillVfxModel.GameplayAction("CircleTelegraph","Radius 3 / Duration 20",Map.of("radius","3"))),visual);
  byte[] authored=SkillVfxEditorProtocol.encodeVisual(visual);assert SkillVfxEditorProtocol.decodeVisual(authored).equals(visual);var request=new SkillVfxEditorProtocol.Request(SkillVfxEditorProtocol.Operation.APPLY_VISUAL_SESSION,9,snapshot.session(),snapshot.abilityId(),snapshot.revision(),snapshot.baseFingerprint(),snapshot.effectiveFingerprint(),authored);var decodedRequest=SkillVfxEditorProtocol.decodeRequest(SkillVfxEditorProtocol.encodeRequest(request));assert decodedRequest.operation()==request.operation()&&decodedRequest.correlation()==9&&java.util.Arrays.equals(authored,decodedRequest.visualBytes());
  var doc=new AbilityVisualEditorDocument(snapshot);assert !doc.dirty();doc.execute(AbilityVisualCommands.setScalar(circle.id(),"radius",new SkillVfxModel.Literal(4)));assert doc.dirty();assert doc.visual().emissions(SkillVfxModel.Hook.TELEGRAPH).getFirst().primitives().getFirst().value("radius") instanceof SkillVfxModel.Literal;assert doc.undo();assert doc.visual().emissions(SkillVfxModel.Hook.TELEGRAPH).getFirst().primitives().getFirst().value("radius") instanceof SkillVfxModel.FromGameplay;assert doc.redo();doc.acknowledge(snapshot);assert !doc.dirty();
  var preview=SkillVfxPreviewBuilder.build(snapshot,visual,SkillVfxModel.Hook.TELEGRAPH,new io.github.gyai.projects.client.vfx.AbilityVfx.Frame(new io.github.gyai.projects.client.vfx.AbilityVfx.Vec(0,0,0),new io.github.gyai.projects.client.vfx.AbilityVfx.Vec(0,0,1),new io.github.gyai.projects.client.vfx.AbilityVfx.Vec(0,1,0)),UUID.randomUUID(),"minecraft:overworld",0);assert preview.valid()&&preview.cue().primitives().getFirst().radius()==3;
  doc.execute(AbilityVisualCommands.duplicate(SkillVfxModel.Hook.TELEGRAPH,"telegraph",circle.id()));assert doc.visual().emissions(SkillVfxModel.Hook.TELEGRAPH).getFirst().primitives().size()==2;assert doc.undo();
  doc.execute(AbilityVisualCommands.addEmission(SkillVfxModel.Hook.TELEGRAPH,new SkillVfxModel.Emission("second",0,List.of(SkillVfxModel.defaults("point-1",SkillVfxModel.PrimitiveType.POINT)))));assert doc.visual().emissions(SkillVfxModel.Hook.TELEGRAPH).size()==2;doc.execute(AbilityVisualCommands.moveEmission(SkillVfxModel.Hook.TELEGRAPH,"second",0));assert doc.visual().emissions(SkillVfxModel.Hook.TELEGRAPH).getFirst().id().equals("second");assert doc.undo();doc.execute(AbilityVisualCommands.movePrimitive(SkillVfxModel.Hook.TELEGRAPH,"telegraph",circle.id(),0));assert doc.undo();doc.execute(AbilityVisualCommands.removeEmission(SkillVfxModel.Hook.TELEGRAPH,"second"));assert doc.undo();
  var timeline=new SkillVfxTimeline();assert timeline.bars(visual,SkillVfxModel.Hook.TELEGRAPH).equals(List.of(new SkillVfxTimeline.Bar("telegraph/telegraph-circle",0,20)));timeline.play();timeline.advance(10,20);assert timeline.ticks()==10;timeline.speed(SkillVfxTimeline.Speed.DOUBLE);timeline.advance(6,20);assert timeline.ticks()==20&&!timeline.playing();
  reorderAndControls();globalPrimitiveIds();
  var layout=new SkillEditorLayout();var bounds=layout.bounds(640,360);assert bounds.tree().width()>=80&&bounds.inspector().width()>=100&&bounds.timeline().height()>=40;layout.dragLeft(999,640);layout.dragRight(0,640);layout.dragBottom(0,360);assert layout.bounds(1,1).preview().width()>=0;layout.visibleTree(false);layout.visibleInspector(false);layout.visibleTimeline(false);layout.reset();assert layout.bounds(640,360).tree().width()>0;assert SkillEditorController.canApply(doc,false,true,true,true);
 }
 private static void reorderAndControls(){
  var first=SkillVfxModel.defaults("first",SkillVfxModel.PrimitiveType.POINT);var line=SkillVfxModel.defaults("line",SkillVfxModel.PrimitiveType.LINE);var bezier=SkillVfxModel.defaults("bezier",SkillVfxModel.PrimitiveType.BEZIER);
  var visual=new SkillVfxModel.Visual("projects:vfx/controls",List.of(new SkillVfxModel.HookBinding(SkillVfxModel.Hook.CAST,List.of(new SkillVfxModel.Emission("cast",-1,List.of(first,line,bezier))))));
  var snapshot=new SkillVfxModel.Snapshot(UUID.randomUUID(),1,"projects:controls","Controls",visual.id(),"base","effective",false,List.of(),visual);var doc=new AbilityVisualEditorDocument(snapshot);doc.select("primitive","line");
  assert line.controls().size()==2;doc.execute(AbilityVisualCommands.movePrimitive(SkillVfxModel.Hook.CAST,"cast","line",0));assert doc.visual().emissions(SkillVfxModel.Hook.CAST).getFirst().primitives().getFirst().id().equals("line")&&doc.selection().primaryId().equals("line")&&doc.dirty();assert doc.undo()&&doc.visual().emissions(SkillVfxModel.Hook.CAST).getFirst().primitives().get(1).id().equals("line");assert doc.redo()&&doc.selection().primaryId().equals("line");
  @SuppressWarnings({"rawtypes","unchecked"}) var lineControl=(io.github.gyai.projects.editor.core.PropertyDescriptor)AbilityVisualPropertySchemas.schema(SkillVfxModel.PrimitiveType.LINE).property("controlPoints");var linePoints=List.of(new SkillVfxModel.Vec(1,2,3),new SkillVfxModel.Vec(4,5,6));lineControl.write(doc,linePoints);assert doc.selectedValue("controlPoints").equals(linePoints)&&doc.undo()&&doc.redo();
  doc.select("primitive","bezier");@SuppressWarnings({"rawtypes","unchecked"}) var bezierControl=(io.github.gyai.projects.editor.core.PropertyDescriptor)AbilityVisualPropertySchemas.schema(SkillVfxModel.PrimitiveType.BEZIER).property("controlPoints");var four=List.of(new SkillVfxModel.Vec(1,0,0),new SkillVfxModel.Vec(2,0,0),new SkillVfxModel.Vec(3,0,0),new SkillVfxModel.Vec(4,0,0));bezierControl.write(doc,four);assert ((List<?>)doc.selectedValue("controlPoints")).size()==4&&doc.undo()&&((List<?>)doc.selectedValue("controlPoints")).size()==3&&doc.redo();
  var preview=SkillVfxPreviewBuilder.build(snapshot,doc.visual(),SkillVfxModel.Hook.CAST,new io.github.gyai.projects.client.vfx.AbilityVfx.Frame(new io.github.gyai.projects.client.vfx.AbilityVfx.Vec(0,0,0),new io.github.gyai.projects.client.vfx.AbilityVfx.Vec(0,0,1),new io.github.gyai.projects.client.vfx.AbilityVfx.Vec(0,1,0)),UUID.randomUUID(),"minecraft:overworld",0);assert preview.valid();var primitives=preview.cue().primitives();var previewLine=primitives.stream().filter(p->p.type()==io.github.gyai.projects.client.vfx.AbilityVfx.Type.LINE).findFirst().orElseThrow();var previewBezier=primitives.stream().filter(p->p.type()==io.github.gyai.projects.client.vfx.AbilityVfx.Type.BEZIER).findFirst().orElseThrow();assert previewLine.controls().size()==2&&previewLine.controls().getFirst().x()==1&&previewLine.controls().get(1).z()==6;assert previewBezier.controls().size()==4&&previewBezier.controls().getLast().x()==4;
 }
 private static void globalPrimitiveIds(){
  var duplicate=SkillVfxModel.defaults("duplicate",SkillVfxModel.PrimitiveType.POINT);boolean rejected=false;try{new SkillVfxModel.Visual("projects:vfx/duplicate",List.of(new SkillVfxModel.HookBinding(SkillVfxModel.Hook.CAST,List.of(new SkillVfxModel.Emission("one",-1,List.of(duplicate)))),new SkillVfxModel.HookBinding(SkillVfxModel.Hook.HIT,List.of(new SkillVfxModel.Emission("two",-1,List.of(duplicate))))));}catch(IllegalArgumentException expected){rejected=true;}assert rejected;
  var unique=new SkillVfxModel.Visual("projects:vfx/unique",List.of(
   new SkillVfxModel.HookBinding(SkillVfxModel.Hook.CAST,List.of(new SkillVfxModel.Emission("one",-1,List.of(duplicate)))),
   new SkillVfxModel.HookBinding(SkillVfxModel.Hook.HIT,List.of(new SkillVfxModel.Emission("two",-1,List.of(SkillVfxModel.defaults("unique",SkillVfxModel.PrimitiveType.POINT)))))
  ));assert unique.emissions(SkillVfxModel.Hook.HIT).size()==1;
 }
}
