package io.github.gyai.projects.devtools.skillvfx;

import io.github.gyai.projects.client.vfx.AbilityVfx;
import io.github.gyai.projects.client.vfx.AbilityVfxLocalPreviewStore;
import java.util.*;

/** Focused non-Minecraft contract checks for v0.3 authoring math and history behavior. */
public final class VfxDirectAuthoringTest {
 public static void main(String[] args){
  var doc=document();var spiral=primitive(doc,"spiral-1");
  // Every guide is the production sampler at complete progress/high quality, not a parallel formula.
  var frame=new AbilityVfx.Frame(new AbilityVfx.Vec(0,0,0),new AbilityVfx.Vec(0,0,1),new AbilityVfx.Vec(0,1,0));
  for(var type:SkillVfxModel.PrimitiveType.values()){var p=SkillVfxModel.defaults(type.name().toLowerCase(),type);assert SkillVfxDirectAuthoring.guide(p,frame).equals(AbilityVfx.sample(SkillVfxPreviewBuilder.convert(p,null),frame,1,AbilityVfx.Quality.HIGH));assert SkillVfxDirectAuthoring.handles(p).stream().anyMatch(h->h.kind().name().startsWith("AXIS"));}var pointGuide=SkillVfxDirectAuthoring.guide(SkillVfxModel.defaults("point-guide",SkillVfxModel.PrimitiveType.POINT),frame);assert pointGuide.size()==1&&pointGuide.getFirst().b()==null&&pointGuide.getFirst().a().equals(AbilityVfx.sample(SkillVfxPreviewBuilder.convert(SkillVfxModel.defaults("point-guide",SkillVfxModel.PrimitiveType.POINT),null),frame,1,AbilityVfx.Quality.HIGH).getFirst().a());
  assert SkillVfxDirectAuthoring.handles(spiral).stream().anyMatch(h->h.id().equals("radius"));
  var tx=SkillVfxDirectAuthoring.DragTransaction.begin(doc,spiral.id()).orElseThrow();tx.update(p->withLiteral(p,"radius",4));assert tx.release();assert doc.history().size()==1;assert literal(primitive(doc,spiral.id()),"radius")==4;assert doc.undo();assert literal(primitive(doc,spiral.id()),"radius")==1;assert doc.redo();assert literal(primitive(doc,spiral.id()),"radius")==4;
  var heightHandle=SkillVfxDirectAuthoring.handles(spiral).stream().filter(h->h.id().equals("height")).findFirst().orElseThrow();var heightProjection=new SkillVfxDirectAuthoring.Projection(new SkillVfxDirectAuthoring.Vec(1,0,0),new SkillVfxDirectAuthoring.Vec(0,1,0),new SkillVfxDirectAuthoring.Vec(0,0,1),new SkillVfxDirectAuthoring.Vec(0,0,-2),100,2);var heightDelta=SkillVfxDirectAuthoring.dragDelta(spiral,heightHandle,frame,heightProjection,0,10,false);assert heightDelta.y()>0;var heightEdited=SkillVfxDirectAuthoring.edit(spiral,heightHandle,0,2,false);assert literal(heightEdited,"height")==3;var heightTx=SkillVfxDirectAuthoring.DragTransaction.begin(doc,spiral.id()).orElseThrow();heightTx.update(p->SkillVfxDirectAuthoring.edit(p,heightHandle,0,2,false));assert heightTx.release()&&doc.history().size()==2;assert literal(primitive(doc,spiral.id()),"height")==3;var heightPreview=SkillVfxPreviewBuilder.convert(primitive(doc,spiral.id()),null);assert AbilityVfx.sample(heightPreview,frame,1,AbilityVfx.Quality.HIGH).stream().anyMatch(c->c.a().y()>0);assert doc.undo()&&literal(primitive(doc,spiral.id()),"height")==1;assert doc.redo()&&literal(primitive(doc,spiral.id()),"height")==3;
  var cancelled=SkillVfxDirectAuthoring.DragTransaction.begin(doc,spiral.id()).orElseThrow();cancelled.update(p->withLiteral(p,"height",5));assert cancelled.cancel();assert doc.history().size()==2;assert literal(primitive(doc,spiral.id()),"height")==3;
  var line=primitive(doc,"line-1");assert line.controls().size()==2;var lineTx=SkillVfxDirectAuthoring.DragTransaction.begin(doc,line.id()).orElseThrow();lineTx.update(p->withControls(p,List.of(new SkillVfxModel.Vec(2,0,0),p.controls().get(1))));assert lineTx.release();assert primitive(doc,line.id()).controls().getFirst().x()==2;
  var lineA=SkillVfxDirectAuthoring.handles(line).stream().filter(h->h.id().equals("control:0")).findFirst().orElseThrow();var lineB=SkillVfxDirectAuthoring.handles(line).stream().filter(h->h.id().equals("control:1")).findFirst().orElseThrow();var editedA=SkillVfxDirectAuthoring.edit(line,lineA,1,2,false);assert editedA.controls().getFirst().equals(new SkillVfxModel.Vec(line.controls().getFirst().x()+1,line.controls().getFirst().y()+2,line.controls().getFirst().z()));var editedB=SkillVfxDirectAuthoring.edit(line,lineB,3,0,true);assert editedB.controls().get(1).z()==line.controls().get(1).z()+3;assert SkillVfxDirectAuthoring.value(editedB,lineB).contains("Z");
  var bezier=primitive(doc,"bezier-1");assert bezier.controls().size()==3;var btx=SkillVfxDirectAuthoring.DragTransaction.begin(doc,bezier.id()).orElseThrow();btx.update(p->withControls(p,List.of(p.controls().get(0),new SkillVfxModel.Vec(0,2,.5),p.controls().get(2))));assert btx.release();assert primitive(doc,bezier.id()).controls().get(1).y()==2;
  var bezier4=withControls(bezier,List.of(bezier.controls().get(0),bezier.controls().get(1),new SkillVfxModel.Vec(1,2,3),bezier.controls().get(2)));for(int i=0;i<4;i++){final int at=i;var h=SkillVfxDirectAuthoring.handles(bezier4).stream().filter(it->it.id().equals("control:"+at)).findFirst().orElseThrow();assert SkillVfxDirectAuthoring.edit(bezier4,h,.25,0,true).controls().get(i).z()==bezier4.controls().get(i).z()+.25;}
  var noop=SkillVfxDirectAuthoring.DragTransaction.begin(doc,spiral.id()).orElseThrow();assert !noop.release()&&doc.history().size()==4;
  var projection=new SkillVfxDirectAuthoring.Projection(new SkillVfxDirectAuthoring.Vec(1,0,0),new SkillVfxDirectAuthoring.Vec(0,1,0),new SkillVfxDirectAuthoring.Vec(0,0,1),new SkillVfxDirectAuthoring.Vec(0,0,0),100,2);var handles=List.of(new SkillVfxDirectAuthoring.Handle("near","",new SkillVfxDirectAuthoring.Vec(0,0,2),SkillVfxDirectAuthoring.Handle.Kind.POINT),new SkillVfxDirectAuthoring.Handle("far","",new SkillVfxDirectAuthoring.Vec(0,0,4),SkillVfxDirectAuthoring.Handle.Kind.POINT));assert SkillVfxDirectAuthoring.pick(handles,projection,0,0,2).orElseThrow().handle().id().equals("near");
  var pitched=SkillVfxDirectAuthoring.fromFov(new SkillVfxDirectAuthoring.Vec(0,.5,.8660254),new SkillVfxDirectAuthoring.Vec(0,1,0),new SkillVfxDirectAuthoring.Vec(0,0,0),Math.PI/2,360,2);assert pitched.project(new SkillVfxDirectAuthoring.Vec(0,1,3)).isPresent();assert SkillVfxDirectAuthoring.fromFov(new SkillVfxDirectAuthoring.Vec(0,0,1),new SkillVfxDirectAuthoring.Vec(0,1,0),new SkillVfxDirectAuthoring.Vec(0,0,0),Math.PI/2,720,2).focal()>pitched.focal();
  assert SkillVfxDirectAuthoring.fromFov(new SkillVfxDirectAuthoring.Vec(0,1,0),new SkillVfxDirectAuthoring.Vec(0,1,0),new SkillVfxDirectAuthoring.Vec(0,0,0),Math.PI/2,360,1).project(new SkillVfxDirectAuthoring.Vec(0,3,0)).isPresent();
  double s=Math.sqrt(.5);var rotatedCamera=SkillVfxDirectAuthoring.fromBasis(new SkillVfxDirectAuthoring.Vec(s,0,-s),new SkillVfxDirectAuthoring.Vec(0,1,0),new SkillVfxDirectAuthoring.Vec(s,0,s),new SkillVfxDirectAuthoring.Vec(-3,0,-3),200);var base=SkillVfxModel.defaults("drag",SkillVfxModel.PrimitiveType.LINE);var dragHandles=SkillVfxDirectAuthoring.worldHandles(base,frame);var dragX=dragHandles.stream().filter(h->h.id().equals("offsetX")).findFirst().orElseThrow();var dragZ=dragHandles.stream().filter(h->h.id().equals("offsetZ")).findFirst().orElseThrow();assert SkillVfxDirectAuthoring.dragDelta(base,dragX,frame,rotatedCamera,12,0,false).x()>0;assert SkillVfxDirectAuthoring.dragDelta(base,dragZ,frame,rotatedCamera,12,0,false).x()<0;var point=dragHandles.stream().filter(h->h.id().equals("control:0")).findFirst().orElseThrow();var plane=SkillVfxDirectAuthoring.dragDelta(base,point,frame,rotatedCamera,8,-5,false);assert Double.isFinite(plane.x())&&Double.isFinite(plane.y())&&(plane.x()!=0||plane.y()!=0);
  var offset=new SkillVfxModel.Primitive("offset",SkillVfxModel.PrimitiveType.SPIRAL,0,20,0xffffffff,.1,16,0,new SkillVfxModel.Vec(2,0,3),Math.PI/2,Map.of("radius",new SkillVfxModel.Literal(1),"turns",new SkillVfxModel.Literal(1)),List.of(),SkillVfxModel.Appearance.DEBUG_QUAD);var worldHandles=SkillVfxDirectAuthoring.worldHandles(offset,frame);var radius=worldHandles.stream().filter(h->h.id().equals("radius")).findFirst().orElseThrow();assert Math.abs(radius.position().x()-2)<1e-6&&Math.abs(radius.position().z()-2)<1e-6;var axisX=worldHandles.stream().filter(h->h.id().equals("offsetX")).findFirst().orElseThrow();assert Math.abs(axisX.position().x()-3)<1e-6&&Math.abs(axisX.position().z()-3)<1e-6;
  for(var type:SkillVfxModel.PrimitiveType.values()){var p=SkillVfxModel.defaults("progress-"+type,type);for(double progress:List.of(0d,.5d,1d))assert SkillVfxDirectAuthoring.guide(p,frame,null,progress).equals(AbilityVfx.sample(SkillVfxPreviewBuilder.convert(p,null),frame,progress,AbilityVfx.Quality.HIGH));}
  assert SkillVfxDirectAuthoring.axisDrag(new SkillVfxDirectAuthoring.Vec(0,0,0),SkillVfxDirectAuthoring.Handle.Kind.AXIS_Y,2).y()==2;
  var life=new SkillVfx3dAuthoringLifecycle();Object screen=new Object(),connection=new Object(),level=new Object();assert life.enter(screen,doc,connection,level,"test:world",spiral.id());assert life.valid(screen,doc,connection,level,"test:world",true);assert !life.valid(screen,doc,new Object(),level,"test:world",true);assert !life.valid(screen,doc,connection,level,"other",true);assert !life.valid(screen,new Object(),connection,level,"test:world",true);life.clear();assert !life.active();
  var action=new SkillVfxModel.GameplayAction("test","test",Map.of("radius","2.5"));var actionPrimitive=SkillVfxModel.defaults("action-circle",SkillVfxModel.PrimitiveType.CIRCLE).withValue("radius",new SkillVfxModel.FromGameplay(SkillVfxModel.ActionField.RADIUS));assert !SkillVfxDirectAuthoring.guide(actionPrimitive,frame,action).isEmpty();previewHistorySync();
  var lengthOnly=withControls(primitive(doc,"line-1"),List.of());doc.replacePrimitive(lengthOnly.id(),lengthOnly);int beforeMaterialize=doc.history().size();assert SkillVfxDirectAuthoring.materializeLine(doc,lengthOnly.id())&&primitive(doc,lengthOnly.id()).controls().size()==2&&doc.history().size()==beforeMaterialize+1;assert doc.undo()&&primitive(doc,lengthOnly.id()).controls().isEmpty();
  var layout=new SkillEditorLayout();java.util.function.ToIntFunction<String> font=text->text.codePointCount(0,text.length())*9;var compact=layout.previewPage(layout.bounds(640,360).preview(),false,"発動時","ベジェ曲線","プレイヤー周囲",true,"",font);assert compact.world().within(layout.bounds(640,360).preview())&&compact.world().width()>=88;
  try{var root=java.nio.file.Path.of("").toAbsolutePath();String editor=java.nio.file.Files.readString(root.resolve("devtools/src/client/java/io/github/gyai/projects/devtools/SkillEditorScreen.java")),authoring=java.nio.file.Files.readString(root.resolve("devtools/src/client/java/io/github/gyai/projects/devtools/skillvfx/ui/SkillVfx3dAuthoringScreen.java")),renderer=java.nio.file.Files.readString(root.resolve("devtools/src/client/java/io/github/gyai/projects/devtools/skillvfx/ui/SkillVfx3dAuthoringWorldRenderer.java")),initializer=java.nio.file.Files.readString(root.resolve("devtools/src/client/java/io/github/gyai/projects/devtools/ProjectSDevTools.java"));assert editor.contains("GLFW.GLFW_KEY_Z")&&editor.contains("GLFW.GLFW_KEY_Y")&&editor.contains("3D編集")&&editor.contains("syncLocalPreview");assert authoring.contains("Alt+ドラッグ")&&authoring.contains("CameraRenderState")&&!authoring.contains("getLookAngle")&&!authoring.contains("grabMouse")&&!authoring.contains("KeyMapping");assert renderer.contains("screen.updateCamera(camera)")&&renderer.contains("PrimitiveType.BEZIER")&&renderer.contains("controls.size()")&&renderer.contains("command.b() == null");assert initializer.contains("SkillVfx3dAuthoringWorldRenderer.register()")&&!java.nio.file.Files.readString(root.resolve("client-core/src/client/java/io/github/gyai/projects/client/ProjectSClient.java")).contains("SkillVfx3dAuthoring");}catch(java.io.IOException e){throw new AssertionError(e);}
 }
 private static AbilityVisualEditorDocument document(){List<SkillVfxModel.Primitive> ps=new ArrayList<>();for(var type:SkillVfxModel.PrimitiveType.values())ps.add(SkillVfxModel.defaults(type.name().toLowerCase()+"-1",type));var visual=new SkillVfxModel.Visual("projects:test",List.of(new SkillVfxModel.HookBinding(SkillVfxModel.Hook.CAST,List.of(new SkillVfxModel.Emission("emission-1",-1,ps)))));return new AbilityVisualEditorDocument(new SkillVfxModel.Snapshot(UUID.randomUUID(),0,"projects:test","Test","projects:test","a","a",false,List.of(),visual));}
 private static SkillVfxModel.Primitive primitive(AbilityVisualEditorDocument d,String id){return SkillVfxMutation.current(d,id).orElseThrow();}
 private static double literal(SkillVfxModel.Primitive p,String key){return p.value(key) instanceof SkillVfxModel.Literal v?v.value():0;}
 private static SkillVfxModel.Primitive withLiteral(SkillVfxModel.Primitive p,String key,double value){return p.withValue(key,new SkillVfxModel.Literal(value));}
 private static SkillVfxModel.Primitive withControls(SkillVfxModel.Primitive p,List<SkillVfxModel.Vec> controls){return new SkillVfxModel.Primitive(p.id(),p.type(),p.delayTicks(),p.durationTicks(),p.argb(),p.width(),p.density(),p.seed(),p.offset(),p.yaw(),p.values(),controls,p.appearance());}
 private static void previewHistorySync(){var d=document();var frame=new AbilityVfx.Frame(new AbilityVfx.Vec(0,0,0),new AbilityVfx.Vec(0,0,1),new AbilityVfx.Vec(0,1,0));var initial=SkillVfxPreviewBuilder.build(d.baseline(),d.visual(),SkillVfxModel.Hook.CAST,frame,UUID.randomUUID(),"minecraft:overworld",0);assert initial.valid();var store=new AbilityVfxLocalPreviewStore();assert store.begin(initial.cue(),0);store.seek(7);store.pause();d.select("primitive","spiral-1");d.execute(AbilityVisualCommands.setAppearance("spiral-1",SkillVfxModel.Appearance.particle("minecraft:flame")));var changed=SkillVfxPreviewBuilder.build(d.baseline(),d.visual(),SkillVfxModel.Hook.CAST,frame,UUID.randomUUID(),"minecraft:overworld",0);assert changed.valid()&&changed.cue().primitives().stream().anyMatch(p->p.appearance().kind()==AbilityVfx.AppearanceKind.PARTICLE);assert store.replaceCuePreservingPlayback(changed.cue());assert store.preview().orElseThrow().tick()==7&&!store.preview().orElseThrow().playing()&&store.preview().orElseThrow().cue().frame().equals(frame)&&store.preview().orElseThrow().cue().primitives().stream().anyMatch(p->p.appearance().kind()==AbilityVfx.AppearanceKind.PARTICLE);assert d.undo();var restored=SkillVfxPreviewBuilder.build(d.baseline(),d.visual(),SkillVfxModel.Hook.CAST,frame,UUID.randomUUID(),"minecraft:overworld",0);assert restored.valid()&&store.replaceCuePreservingPlayback(restored.cue());assert store.preview().orElseThrow().tick()==7&&!store.preview().orElseThrow().playing()&&store.preview().orElseThrow().cue().primitives().stream().allMatch(p->p.appearance().kind()==AbilityVfx.AppearanceKind.DEBUG_QUAD);int before=d.visual().emissions(SkillVfxModel.Hook.CAST).getFirst().primitives().size();d.execute(AbilityVisualCommands.remove(SkillVfxModel.Hook.CAST,"emission-1","spiral-1",null));var structural=SkillVfxPreviewBuilder.build(d.baseline(),d.visual(),SkillVfxModel.Hook.CAST,frame,UUID.randomUUID(),"minecraft:overworld",0);assert structural.valid()&&structural.cue().primitives().size()==before-1&&store.replaceCuePreservingPlayback(structural.cue());assert store.preview().orElseThrow().tick()==7&&!store.preview().orElseThrow().playing();assert d.undo();var structuralUndo=SkillVfxPreviewBuilder.build(d.baseline(),d.visual(),SkillVfxModel.Hook.CAST,frame,UUID.randomUUID(),"minecraft:overworld",0);assert structuralUndo.valid()&&structuralUndo.cue().primitives().size()==before;}
}
